#!/bin/sh
set -x

# init-premount script for ADE
# relies on the initramfs environment to have been prepared such that 
# /etc/fstab is ready to mount the boot partition and key volume that
# cryptsetup uses to open encrypted root device /dev/mapper/osencrypt
# The hook script is here: /usr/share/initramfs-tools/hooks/crypt-ade

PREREQS="udev"
prereqs()
{
        echo $PREREQS
}

mount -a
cryptsetup luksOpen /dev/disk/azure/root-part1 osencrypt --header /boot/luks/osluksheader -d /mnt/azure_bek_disk/LinuxPassPhraseFileName

exit 0