""" list of Linux OS image skus where ADE OS Disk encryption is unsupported """
unsupported_images_ade_os_encryption = [
      ("RHEL", "6.8"),
      ("RHEL", "6.7"),
      ("CentOS", "7.1"),    
      ("CentOS", "7.0"),
      ("CentOS", "6.8"),
      ("openSUSE", "42.3"),
      ("SLES", "12-SP4"),
      ("SLES", "12-SP3"),
      ("SLES-HPC", "12-SP3")]

""" list of VM Skus unsupported by HBE """
unsupported_vm_sku_hbe_encryption = [
    "Basic_A0",
    "Basic_A1",
    "Basic_A2",
    "Basic_A3",
    "Basic_A4",
    "Standard_A0",
    "Standard_A1",
    "Standard_A1_v2",
    "Standard_A2",
    "Standard_A2m_v2",
    "Standard_A2_v2",
    "Standard_A3",
    "Standard_A4",
    "Standard_A4m_v2",
    "Standard_A4_v2",
    "Standard_A5",
    "Standard_A6",
    "Standard_A7",
    "Standard_A8m_v2",
    "Standard_A8_v2",
    "Standard_D11_v2",
    "Standard_D11_v2_Promo",
    "Standard_D12_v2",
    "Standard_D12_v2_Promo",
    "Standard_D13_v2",
    "Standard_D13_v2_Promo",
    "Standard_D14_v2",
    "Standard_D14_v2_Promo",
    "Standard_D15_v2",
    "Standard_D16_v3",
    "Standard_D16_v4",
    "Standard_D1_v2",
    "Standard_D2_v2",
    "Standard_D2_v2_Promo",
    "Standard_D2_v3",
    "Standard_D2_v4",
    "Standard_D32_v3",
    "Standard_D32_v4",
    "Standard_D3_v2",
    "Standard_D3_v2_Promo",
    "Standard_D48_v3",
    "Standard_D48_v4",
    "Standard_D4_v2",
    "Standard_D4_v2_Promo",
    "Standard_D4_v3",
    "Standard_D4_v4",
    "Standard_D5_v2",
    "Standard_D5_v2_Promo",
    "Standard_D64_v3",
    "Standard_D64_v4",
    "Standard_D8_v3",
    "Standard_D8_v4",
    "Standard_E16_v3",
    "Standard_E16_v4",
    "Standard_E20_v3",
    "Standard_E20_v4",
    "Standard_E2_v3",
    "Standard_E2_v4",
    "Standard_E32_v3",
    "Standard_E32_v4",
    "Standard_E48_v3",
    "Standard_E48_v4",
    "Standard_E4_v3",
    "Standard_E4_v4",
    "Standard_E64i_v3",
    "Standard_E64_v3",
    "Standard_E64_v4",
    "Standard_E8_v3",
    "Standard_E8_v4",
    "Standard_F1",
    "Standard_F16",
    "Standard_F2",
    "Standard_F4",
    "Standard_F8",
    "Standard_G1",
    "Standard_G2",
    "Standard_G3",
    "Standard_G4",
    "Standard_G5"
    ]

""" list of Linux OS image skus supported by ADE """
supported_ade_image_list = [
      ("0001-com-ubuntu-server-focal", "20_04-lts"),
      ("0001-com-ubuntu-server-focal-daily", "20_04-daily-lts"),
      ("0001-com-ubuntu-server-focal", "20_04-lts-gen2"),    
      ("0001-com-ubuntu-server-focal-daily", "20_04-daily-lts-gen2"),
      ("UbuntuServer", "18.04-LTS"),
      ("UbuntuServer", "18.04-DAILY-LTS"),
      ("UbuntuServer", "16.04-LTS"),
      ("UbuntuServer", "16.04-DAILY-LTS"),
      ("UbuntuServer", "14.04.5-LTS"),
      ("UbuntuServer", "14.04.5-DAILY-LTS"),      
      ("RHEL", "8.4"),
      ("RHEL", "8.3"),
      ("RHEL", "8-LVM"),
      ("RHEL", "8.2"),
      ("RHEL", "8.1"),
      ("RHEL", "7-LVM"),
      ("RHEL", "7_9"),
      ("RHEL", "7.8"),
      ("RHEL", "7.7"),
      ("RHEL", "7.6"),
      ("RHEL", "7.5"),
      ("RHEL", "7.4"),
      ("RHEL", "7.3"),
      ("RHEL", "7.2"),
      ("RHEL", "6.8"),
      ("RHEL", "6.7"),
      ("CentOS-LVM", "8-LVM"),
      ("CentOS", "8_4"),      
      ("CentOS", "8_3"),
      ("CentOS", "8_2"),
      ("CentOS", "8_1"),
      ("CentOS-LVM", "7-LVM"),      
      ("CentOS", "7_9"),
      ("CentOS", "7_8"),
      ("CentOS", "7.7"),
      ("CentOS", "7.6"),      
      ("CentOS", "7.5"),
      ("CentOS", "7.4"),
      ("CentOS", "7.3"),    
      ("CentOS", "7.2n"),
      ("CentOS", "7.1"),
      ("CentOS", "7.0"),
      ("CentOS", "6.8"),      
      ("openSUSE-Leap", "42.3"),
      ("SLES", "12-SP4"),
      ("SLES", "12-SP3"),
      ("SLES-HPC", "12-SP3")
]
