receivers:
  vmmetrics:
    scrape_interval: 10
    mount_point: "/proc"
    # process_mount_point: "/data/proc" # Should only be used for Daemon Set within a container.

zpages:
  port: 55679

exporters:
  prometheus:
    namespace: "vmmetrics_test"
    address: "localhost:8888"
